# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AGV.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 580)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        MainWindow.setMaximumSize(QtCore.QSize(15000, 15000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/optimak.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(130, 250, 130);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tabWidgetEtiketOzellikleri = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetEtiketOzellikleri.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidgetEtiketOzellikleri.setFont(font)
        self.tabWidgetEtiketOzellikleri.setStyleSheet("background-color: rgb(120, 250, 120);\n"
"color: rgb(27, 27, 36);\n"
"")
        self.tabWidgetEtiketOzellikleri.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidgetEtiketOzellikleri.setObjectName("tabWidgetEtiketOzellikleri")
        self.ANASAYFA = QtWidgets.QWidget()
        self.ANASAYFA.setStyleSheet("")
        self.ANASAYFA.setObjectName("ANASAYFA")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ANASAYFA)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_ust = QtWidgets.QFrame(self.ANASAYFA)
        self.frame_ust.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_ust.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_ust.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ust.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ust.setObjectName("frame_ust")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_ust)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_ust)
        self.frame.setMinimumSize(QtCore.QSize(250, 150))
        self.frame.setMaximumSize(QtCore.QSize(300, 220))
        self.frame.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border-radius: 20px;\n"
"border: 3px solid  rgb(0, 120, 10);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_48 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setMinimumSize(QtCore.QSize(50, 30))
        self.label_48.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("border:none;")
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 4, 0, 1, 1)
        self.labelAMR1Status = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAMR1Status.sizePolicy().hasHeightForWidth())
        self.labelAMR1Status.setSizePolicy(sizePolicy)
        self.labelAMR1Status.setMinimumSize(QtCore.QSize(60, 30))
        self.labelAMR1Status.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelAMR1Status.setFont(font)
        self.labelAMR1Status.setStyleSheet("border:none;background-color:rgb(255,0,0);border-radius:12px;")
        self.labelAMR1Status.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAMR1Status.setWordWrap(True)
        self.labelAMR1Status.setIndent(1)
        self.labelAMR1Status.setObjectName("labelAMR1Status")
        self.gridLayout.addWidget(self.labelAMR1Status, 4, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMinimumSize(QtCore.QSize(50, 30))
        self.label_49.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("border:none;")
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 5, 0, 1, 1)
        self.labelAMR2Status = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAMR2Status.sizePolicy().hasHeightForWidth())
        self.labelAMR2Status.setSizePolicy(sizePolicy)
        self.labelAMR2Status.setMinimumSize(QtCore.QSize(60, 30))
        self.labelAMR2Status.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setBold(True)
        font.setWeight(75)
        self.labelAMR2Status.setFont(font)
        self.labelAMR2Status.setStyleSheet("border:none;background-color:rgb(255,0,0);border-radius:15px;")
        self.labelAMR2Status.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAMR2Status.setWordWrap(True)
        self.labelAMR2Status.setObjectName("labelAMR2Status")
        self.gridLayout.addWidget(self.labelAMR2Status, 5, 2, 1, 1)
        self.radioButtonBaglantiDurumlari = QtWidgets.QRadioButton(self.frame)
        self.radioButtonBaglantiDurumlari.setMaximumSize(QtCore.QSize(30, 30))
        self.radioButtonBaglantiDurumlari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButtonBaglantiDurumlari.setStyleSheet("border:none;")
        self.radioButtonBaglantiDurumlari.setText("")
        self.radioButtonBaglantiDurumlari.setChecked(False)
        self.radioButtonBaglantiDurumlari.setAutoRepeat(False)
        self.radioButtonBaglantiDurumlari.setObjectName("radioButtonBaglantiDurumlari")
        self.gridLayout.addWidget(self.radioButtonBaglantiDurumlari, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 30))
        self.label_6.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border:none;")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.labelPLCStatus = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPLCStatus.sizePolicy().hasHeightForWidth())
        self.labelPLCStatus.setSizePolicy(sizePolicy)
        self.labelPLCStatus.setMinimumSize(QtCore.QSize(60, 30))
        self.labelPLCStatus.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setBold(True)
        font.setWeight(75)
        self.labelPLCStatus.setFont(font)
        self.labelPLCStatus.setStyleSheet("border:none;background-color:rgb(255,0,0);border-radius:15px;")
        self.labelPLCStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPLCStatus.setWordWrap(True)
        self.labelPLCStatus.setObjectName("labelPLCStatus")
        self.gridLayout.addWidget(self.labelPLCStatus, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)
        self.labelCevrimSuresi = QtWidgets.QLabel(self.frame)
        self.labelCevrimSuresi.setMinimumSize(QtCore.QSize(50, 30))
        self.labelCevrimSuresi.setMaximumSize(QtCore.QSize(100, 30))
        self.labelCevrimSuresi.setStyleSheet("border:none;")
        self.labelCevrimSuresi.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCevrimSuresi.setObjectName("labelCevrimSuresi")
        self.gridLayout.addWidget(self.labelCevrimSuresi, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setMinimumSize(QtCore.QSize(50, 30))
        self.label_10.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border:none;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.butonKapat = QtWidgets.QPushButton(self.frame_ust)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butonKapat.sizePolicy().hasHeightForWidth())
        self.butonKapat.setSizePolicy(sizePolicy)
        self.butonKapat.setMinimumSize(QtCore.QSize(100, 50))
        self.butonKapat.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.butonKapat.setFont(font)
        self.butonKapat.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/close_icon.png);\n"
"\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.butonKapat.setIconSize(QtCore.QSize(30, 30))
        self.butonKapat.setObjectName("butonKapat")
        self.gridLayout_2.addWidget(self.butonKapat, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_ust)
        self.label_22.setStyleSheet("border-image: url(:/images/icons/araclar.png);\n"
"border-radius: 20px;\n"
"border: 5px solid  rgb(71, 71, 95);")
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.butonlarWidget = QtWidgets.QWidget(self.frame_ust)
        self.butonlarWidget.setMinimumSize(QtCore.QSize(200, 199))
        self.butonlarWidget.setMaximumSize(QtCore.QSize(200, 220))
        self.butonlarWidget.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border-radius: 20px;\n"
"border: 3px solid  rgb(0, 120, 10);\n"
"")
        self.butonlarWidget.setObjectName("butonlarWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.butonlarWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelYazdirmaZamani = QtWidgets.QLabel(self.butonlarWidget)
        self.labelYazdirmaZamani.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelYazdirmaZamani.setFont(font)
        self.labelYazdirmaZamani.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYazdirmaZamani.setObjectName("labelYazdirmaZamani")
        self.horizontalLayout_6.addWidget(self.labelYazdirmaZamani)
        self.labelSonBarkodunBasilmaDurumu = QtWidgets.QLabel(self.butonlarWidget)
        self.labelSonBarkodunBasilmaDurumu.setMinimumSize(QtCore.QSize(40, 40))
        self.labelSonBarkodunBasilmaDurumu.setMaximumSize(QtCore.QSize(40, 40))
        self.labelSonBarkodunBasilmaDurumu.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 5px solid;\n"
"border-radius: 15px;\n"
"")
        self.labelSonBarkodunBasilmaDurumu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSonBarkodunBasilmaDurumu.setObjectName("labelSonBarkodunBasilmaDurumu")
        self.horizontalLayout_6.addWidget(self.labelSonBarkodunBasilmaDurumu)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.pushButtonRefresh = QtWidgets.QPushButton(self.butonlarWidget)
        self.pushButtonRefresh.setEnabled(True)
        self.pushButtonRefresh.setMinimumSize(QtCore.QSize(180, 50))
        self.pushButtonRefresh.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRefresh.setFont(font)
        self.pushButtonRefresh.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    qproperty-icon: url(:/images/icons/refresh_icon.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.pushButtonRefresh.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.verticalLayout_6.addWidget(self.pushButtonRefresh)
        self.horizontalLayout.addWidget(self.butonlarWidget)
        self.verticalLayout_7.addWidget(self.frame_ust)
        self.frame_log = QtWidgets.QFrame(self.ANASAYFA)
        self.frame_log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_log.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_log.setObjectName("frame_log")
        self.listWidgetLog = QtWidgets.QListWidget(self.frame_log)
        self.listWidgetLog.setGeometry(QtCore.QRect(10, 10, 700, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetLog.sizePolicy().hasHeightForWidth())
        self.listWidgetLog.setSizePolicy(sizePolicy)
        self.listWidgetLog.setMinimumSize(QtCore.QSize(700, 200))
        self.listWidgetLog.setMaximumSize(QtCore.QSize(700, 700))
        self.listWidgetLog.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(230, 230, 230);\n"
"border: 5px solid  rgb(0, 120, 10);\n"
"")
        self.listWidgetLog.setObjectName("listWidgetLog")
        self.verticalLayout_7.addWidget(self.frame_log)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/homepage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetEtiketOzellikleri.addTab(self.ANASAYFA, icon1, "")
        self.DATALAR = QtWidgets.QWidget()
        self.DATALAR.setObjectName("DATALAR")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DATALAR)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.DATALAR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 38))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 120, 10);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid;\n"
"    border-radius: 10px ;\n"
"}")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 6, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.buton_ileri = QtWidgets.QPushButton(self.frame_2)
        self.buton_ileri.setMinimumSize(QtCore.QSize(0, 50))
        self.buton_ileri.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buton_ileri.setFont(font)
        self.buton_ileri.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 3px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton::checked\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.buton_ileri.setCheckable(False)
        self.buton_ileri.setObjectName("buton_ileri")
        self.gridLayout_5.addWidget(self.buton_ileri, 1, 1, 1, 1)
        self.buton_geri = QtWidgets.QPushButton(self.frame_2)
        self.buton_geri.setMinimumSize(QtCore.QSize(0, 50))
        self.buton_geri.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buton_geri.setFont(font)
        self.buton_geri.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 3px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton::checked\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.buton_geri.setCheckable(False)
        self.buton_geri.setObjectName("buton_geri")
        self.gridLayout_5.addWidget(self.buton_geri, 3, 1, 1, 1)
        self.buton_dur = QtWidgets.QPushButton(self.frame_2)
        self.buton_dur.setMinimumSize(QtCore.QSize(0, 50))
        self.buton_dur.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buton_dur.setFont(font)
        self.buton_dur.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 3px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.buton_dur.setCheckable(True)
        self.buton_dur.setObjectName("buton_dur")
        self.gridLayout_5.addWidget(self.buton_dur, 2, 1, 1, 1)
        self.buton_sol = QtWidgets.QPushButton(self.frame_2)
        self.buton_sol.setMinimumSize(QtCore.QSize(0, 50))
        self.buton_sol.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buton_sol.setFont(font)
        self.buton_sol.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 3px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton::checked\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.buton_sol.setCheckable(False)
        self.buton_sol.setObjectName("buton_sol")
        self.gridLayout_5.addWidget(self.buton_sol, 2, 0, 1, 1)
        self.buton_sag = QtWidgets.QPushButton(self.frame_2)
        self.buton_sag.setMinimumSize(QtCore.QSize(0, 50))
        self.buton_sag.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buton_sag.setFont(font)
        self.buton_sag.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 3px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton::checked\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.buton_sag.setCheckable(False)
        self.buton_sag.setObjectName("buton_sag")
        self.gridLayout_5.addWidget(self.buton_sag, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 8, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_4.addWidget(self.widget, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(29)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_lineer_hiz = QtWidgets.QLineEdit(self.tab_1)
        self.label_lineer_hiz.setObjectName("label_lineer_hiz")
        self.gridLayout_24.addWidget(self.label_lineer_hiz, 0, 1, 1, 1)
        self.label_donus_acisi = QtWidgets.QLineEdit(self.tab_1)
        self.label_donus_acisi.setObjectName("label_donus_acisi")
        self.gridLayout_24.addWidget(self.label_donus_acisi, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_24.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_konum_y = QtWidgets.QLineEdit(self.tab_1)
        self.label_konum_y.setObjectName("label_konum_y")
        self.gridLayout_24.addWidget(self.label_konum_y, 3, 1, 1, 1)
        self.label_konum_x = QtWidgets.QLineEdit(self.tab_1)
        self.label_konum_x.setObjectName("label_konum_x")
        self.gridLayout_24.addWidget(self.label_konum_x, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_24.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_24.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_acisal_hiz = QtWidgets.QLineEdit(self.tab_1)
        self.label_acisal_hiz.setObjectName("label_acisal_hiz")
        self.gridLayout_24.addWidget(self.label_acisal_hiz, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_24.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_24.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_24.addWidget(self.label_19, 5, 0, 1, 1)
        self.label_amr1_sarj_durumu = QtWidgets.QLineEdit(self.tab_1)
        self.label_amr1_sarj_durumu.setObjectName("label_amr1_sarj_durumu")
        self.gridLayout_24.addWidget(self.label_amr1_sarj_durumu, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_lineer_hiz_2 = QtWidgets.QLineEdit(self.tab_2)
        self.label_lineer_hiz_2.setObjectName("label_lineer_hiz_2")
        self.gridLayout_14.addWidget(self.label_lineer_hiz_2, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_14.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_konum_x_2 = QtWidgets.QLineEdit(self.tab_2)
        self.label_konum_x_2.setObjectName("label_konum_x_2")
        self.gridLayout_14.addWidget(self.label_konum_x_2, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_14.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_konum_y_2 = QtWidgets.QLineEdit(self.tab_2)
        self.label_konum_y_2.setObjectName("label_konum_y_2")
        self.gridLayout_14.addWidget(self.label_konum_y_2, 3, 1, 1, 1)
        self.label_acisal_hiz_2 = QtWidgets.QLineEdit(self.tab_2)
        self.label_acisal_hiz_2.setObjectName("label_acisal_hiz_2")
        self.gridLayout_14.addWidget(self.label_acisal_hiz_2, 1, 1, 1, 1)
        self.label_donus_acisi_2 = QtWidgets.QLineEdit(self.tab_2)
        self.label_donus_acisi_2.setObjectName("label_donus_acisi_2")
        self.gridLayout_14.addWidget(self.label_donus_acisi_2, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_14.addWidget(self.label_23, 5, 0, 1, 1)
        self.label_amr2_sarj_durumu = QtWidgets.QLineEdit(self.tab_2)
        self.label_amr2_sarj_durumu.setObjectName("label_amr2_sarj_durumu")
        self.gridLayout_14.addWidget(self.label_amr2_sarj_durumu, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_25 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_30 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_26 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_lineer_hiz_toplam = QtWidgets.QLineEdit(self.widget1)
        self.label_lineer_hiz_toplam.setObjectName("label_lineer_hiz_toplam")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_lineer_hiz_toplam)
        self.label_acisal_hiz_toplam = QtWidgets.QLineEdit(self.widget1)
        self.label_acisal_hiz_toplam.setObjectName("label_acisal_hiz_toplam")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_acisal_hiz_toplam)
        self.label_konum_x_toplam = QtWidgets.QLineEdit(self.widget1)
        self.label_konum_x_toplam.setObjectName("label_konum_x_toplam")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_konum_x_toplam)
        self.label_konum_y_toplam = QtWidgets.QLineEdit(self.widget1)
        self.label_konum_y_toplam.setObjectName("label_konum_y_toplam")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_konum_y_toplam)
        self.label_donus_acisi_toplam = QtWidgets.QLineEdit(self.widget1)
        self.label_donus_acisi_toplam.setObjectName("label_donus_acisi_toplam")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_donus_acisi_toplam)
        self.horizontalLayout_5.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_36 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.label_37 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.label_38 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.label_39 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.label_40 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.label_lineer_hiz_toplam_2 = QtWidgets.QLineEdit(self.widget1)
        self.label_lineer_hiz_toplam_2.setObjectName("label_lineer_hiz_toplam_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_lineer_hiz_toplam_2)
        self.label_acisal_hiz_toplam_2 = QtWidgets.QLineEdit(self.widget1)
        self.label_acisal_hiz_toplam_2.setObjectName("label_acisal_hiz_toplam_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_acisal_hiz_toplam_2)
        self.label_konum_x_toplam_2 = QtWidgets.QLineEdit(self.widget1)
        self.label_konum_x_toplam_2.setObjectName("label_konum_x_toplam_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_konum_x_toplam_2)
        self.label_konum_y_toplam_2 = QtWidgets.QLineEdit(self.widget1)
        self.label_konum_y_toplam_2.setObjectName("label_konum_y_toplam_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_konum_y_toplam_2)
        self.label_donus_acisi_toplam_2 = QtWidgets.QLineEdit(self.widget1)
        self.label_donus_acisi_toplam_2.setObjectName("label_donus_acisi_toplam_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_donus_acisi_toplam_2)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.tabWidget.addTab(self.widget1, "")
        self.gridLayout_4.addWidget(self.tabWidget, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_agv_goruntu = QtWidgets.QLabel(self.DATALAR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_agv_goruntu.sizePolicy().hasHeightForWidth())
        self.label_agv_goruntu.setSizePolicy(sizePolicy)
        self.label_agv_goruntu.setMinimumSize(QtCore.QSize(300, 300))
        self.label_agv_goruntu.setMaximumSize(QtCore.QSize(500, 405))
        self.label_agv_goruntu.setText("")
        self.label_agv_goruntu.setScaledContents(True)
        self.label_agv_goruntu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_agv_goruntu.setObjectName("label_agv_goruntu")
        self.verticalLayout_3.addWidget(self.label_agv_goruntu)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.butonKapat_5 = QtWidgets.QPushButton(self.DATALAR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butonKapat_5.sizePolicy().hasHeightForWidth())
        self.butonKapat_5.setSizePolicy(sizePolicy)
        self.butonKapat_5.setMinimumSize(QtCore.QSize(0, 50))
        self.butonKapat_5.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.butonKapat_5.setFont(font)
        self.butonKapat_5.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/close_icon.png);\n"
"\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.butonKapat_5.setIconSize(QtCore.QSize(30, 30))
        self.butonKapat_5.setObjectName("butonKapat_5")
        self.gridLayout_8.addWidget(self.butonKapat_5, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/agv_icons.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetEtiketOzellikleri.addTab(self.DATALAR, icon2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_10.addWidget(self.label_41, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_47 = QtWidgets.QLabel(self.tab_4)
        self.label_47.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("border: 3px solid  rgb(0, 120, 10);\n"
"border-radius: 10px;\n"
"border-radius:15px;\n"
"background-color: rgb(230, 230, 230);\n"
"")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_9.addWidget(self.label_47)
        self.tableWidget_durak_listesi = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_durak_listesi.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_durak_listesi.setFont(font)
        self.tableWidget_durak_listesi.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: 1px solid  rgb(0, 120, 10);\n"
"")
        self.tableWidget_durak_listesi.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_durak_listesi.setObjectName("tableWidget_durak_listesi")
        self.tableWidget_durak_listesi.setColumnCount(5)
        self.tableWidget_durak_listesi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_durak_listesi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_durak_listesi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_durak_listesi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_durak_listesi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_durak_listesi.setHorizontalHeaderItem(4, item)
        self.tableWidget_durak_listesi.horizontalHeader().setDefaultSectionSize(100)
        self.verticalLayout_9.addWidget(self.tableWidget_durak_listesi)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_durak_sayici = QtWidgets.QLabel(self.tab_4)
        self.label_durak_sayici.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_durak_sayici.setFont(font)
        self.label_durak_sayici.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.label_durak_sayici.setAlignment(QtCore.Qt.AlignCenter)
        self.label_durak_sayici.setObjectName("label_durak_sayici")
        self.horizontalLayout_3.addWidget(self.label_durak_sayici)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushbuton_durak_liste_yenile = QtWidgets.QPushButton(self.tab_4)
        self.pushbuton_durak_liste_yenile.setMinimumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushbuton_durak_liste_yenile.setFont(font)
        self.pushbuton_durak_liste_yenile.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/refresh_icon.png);\n"
"    background-color: rgb(0, 120, 10);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushbuton_durak_liste_yenile.setIconSize(QtCore.QSize(30, 30))
        self.pushbuton_durak_liste_yenile.setObjectName("pushbuton_durak_liste_yenile")
        self.horizontalLayout_3.addWidget(self.pushbuton_durak_liste_yenile)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_durak_log = QtWidgets.QLabel(self.tab_4)
        self.label_durak_log.setMinimumSize(QtCore.QSize(0, 50))
        self.label_durak_log.setToolTipDuration(-3)
        self.label_durak_log.setTextFormat(QtCore.Qt.AutoText)
        self.label_durak_log.setAlignment(QtCore.Qt.AlignCenter)
        self.label_durak_log.setObjectName("label_durak_log")
        self.verticalLayout_10.addWidget(self.label_durak_log)
        self.frame_7 = QtWidgets.QFrame(self.tab_4)
        self.frame_7.setStyleSheet("border: 3px solid  rgb(0, 120, 10);\n"
"border-radius: 10px;\n"
"background-color: rgb(230, 230, 230);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem6, 11, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem7, 15, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame_7)
        self.label_42.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_42.setStyleSheet("border: none ;")
        self.label_42.setScaledContents(False)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_12.addWidget(self.label_42, 3, 0, 1, 1)
        self.comboBox_amr_secim = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_amr_secim.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_amr_secim.setFont(font)
        self.comboBox_amr_secim.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.comboBox_amr_secim.setObjectName("comboBox_amr_secim")
        self.comboBox_amr_secim.addItem("")
        self.comboBox_amr_secim.addItem("")
        self.comboBox_amr_secim.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_amr_secim, 0, 0, 1, 1)
        self.lineEdit_durak_kaydet_durak_notu = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_durak_kaydet_durak_notu.setMinimumSize(QtCore.QSize(0, 22))
        self.lineEdit_durak_kaydet_durak_notu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.lineEdit_durak_kaydet_durak_notu.setObjectName("lineEdit_durak_kaydet_durak_notu")
        self.gridLayout_12.addWidget(self.lineEdit_durak_kaydet_durak_notu, 14, 1, 1, 2)
        self.lineEdit_durak_kaydet_durak_ismi = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_durak_kaydet_durak_ismi.setMinimumSize(QtCore.QSize(0, 22))
        self.lineEdit_durak_kaydet_durak_ismi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.lineEdit_durak_kaydet_durak_ismi.setObjectName("lineEdit_durak_kaydet_durak_ismi")
        self.gridLayout_12.addWidget(self.lineEdit_durak_kaydet_durak_ismi, 13, 1, 1, 2)
        self.label_45 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("border : none;")
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_12.addWidget(self.label_45, 14, 0, 1, 1)
        self.pushButton_durak_kaydet = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_durak_kaydet.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_durak_kaydet.setFont(font)
        self.pushButton_durak_kaydet.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/save-icon.png);\n"
"    background-color: rgb(0, 120, 10);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButton_durak_kaydet.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_durak_kaydet.setObjectName("pushButton_durak_kaydet")
        self.gridLayout_12.addWidget(self.pushButton_durak_kaydet, 15, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("border : none;")
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_12.addWidget(self.label_44, 12, 0, 2, 1)
        self.label_90 = QtWidgets.QLabel(self.frame_7)
        self.label_90.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_90.setFont(font)
        self.label_90.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_90.setStyleSheet("border: none ;")
        self.label_90.setScaledContents(False)
        self.label_90.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_90.setObjectName("label_90")
        self.gridLayout_12.addWidget(self.label_90, 6, 0, 1, 1)
        self.label_durak_kaydet_mevcut_konum = QtWidgets.QLabel(self.frame_7)
        self.label_durak_kaydet_mevcut_konum.setMinimumSize(QtCore.QSize(0, 22))
        self.label_durak_kaydet_mevcut_konum.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.label_durak_kaydet_mevcut_konum.setText("")
        self.label_durak_kaydet_mevcut_konum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_durak_kaydet_mevcut_konum.setWordWrap(True)
        self.label_durak_kaydet_mevcut_konum.setObjectName("label_durak_kaydet_mevcut_konum")
        self.gridLayout_12.addWidget(self.label_durak_kaydet_mevcut_konum, 3, 1, 1, 2)
        self.label_durak_kaydet_mevcut_konum_2 = QtWidgets.QLabel(self.frame_7)
        self.label_durak_kaydet_mevcut_konum_2.setMinimumSize(QtCore.QSize(0, 22))
        self.label_durak_kaydet_mevcut_konum_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.label_durak_kaydet_mevcut_konum_2.setText("")
        self.label_durak_kaydet_mevcut_konum_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_durak_kaydet_mevcut_konum_2.setWordWrap(True)
        self.label_durak_kaydet_mevcut_konum_2.setObjectName("label_durak_kaydet_mevcut_konum_2")
        self.gridLayout_12.addWidget(self.label_durak_kaydet_mevcut_konum_2, 6, 1, 1, 2)
        self.verticalLayout_10.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.tab_4)
        self.frame_8.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: 3px solid  rgb(0, 120, 10);\n"
"border-radius: 10px;\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem8, 7, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_8)
        self.label_46.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("border: none;")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_13.addWidget(self.label_46, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem9, 7, 2, 1, 1)
        self.pushButton_durak_sil = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_durak_sil.setMinimumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_durak_sil.setFont(font)
        self.pushButton_durak_sil.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/delete.png);\n"
"    background-color: rgb(0, 120, 10);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButton_durak_sil.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_durak_sil.setObjectName("pushButton_durak_sil")
        self.gridLayout_13.addWidget(self.pushButton_durak_sil, 7, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem10, 6, 1, 1, 1)
        self.comboBox_durak_sil_liste = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_durak_sil_liste.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_durak_sil_liste.setFont(font)
        self.comboBox_durak_sil_liste.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.comboBox_durak_sil_liste.setObjectName("comboBox_durak_sil_liste")
        self.gridLayout_13.addWidget(self.comboBox_durak_sil_liste, 2, 0, 1, 3)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.butonKapat_4 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butonKapat_4.sizePolicy().hasHeightForWidth())
        self.butonKapat_4.setSizePolicy(sizePolicy)
        self.butonKapat_4.setMinimumSize(QtCore.QSize(0, 50))
        self.butonKapat_4.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.butonKapat_4.setFont(font)
        self.butonKapat_4.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/close_icon.png);\n"
"\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.butonKapat_4.setIconSize(QtCore.QSize(30, 30))
        self.butonKapat_4.setObjectName("butonKapat_4")
        self.horizontalLayout_9.addWidget(self.butonKapat_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetEtiketOzellikleri.addTab(self.tab_4, icon3, "")
        self.AYARLAR = QtWidgets.QWidget()
        self.AYARLAR.setObjectName("AYARLAR")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.AYARLAR)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.pushButtonGirisYap = QtWidgets.QPushButton(self.AYARLAR)
        self.pushButtonGirisYap.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButtonGirisYap.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonGirisYap.setFont(font)
        self.pushButtonGirisYap.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"\n"
"}")
        self.pushButtonGirisYap.setObjectName("pushButtonGirisYap")
        self.horizontalLayout_2.addWidget(self.pushButtonGirisYap)
        self.pushButtonCikisYap = QtWidgets.QPushButton(self.AYARLAR)
        self.pushButtonCikisYap.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButtonCikisYap.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCikisYap.setFont(font)
        self.pushButtonCikisYap.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButtonCikisYap.setObjectName("pushButtonCikisYap")
        self.horizontalLayout_2.addWidget(self.pushButtonCikisYap)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.butonKapat_3 = QtWidgets.QPushButton(self.AYARLAR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butonKapat_3.sizePolicy().hasHeightForWidth())
        self.butonKapat_3.setSizePolicy(sizePolicy)
        self.butonKapat_3.setMinimumSize(QtCore.QSize(0, 50))
        self.butonKapat_3.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.butonKapat_3.setFont(font)
        self.butonKapat_3.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/close_icon.png);\n"
"\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.butonKapat_3.setIconSize(QtCore.QSize(30, 30))
        self.butonKapat_3.setObjectName("butonKapat_3")
        self.horizontalLayout_8.addWidget(self.butonKapat_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        self.widgetSifreli = QtWidgets.QWidget(self.AYARLAR)
        self.widgetSifreli.setEnabled(True)
        self.widgetSifreli.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: 3px solid  rgb(0, 0, 0);")
        self.widgetSifreli.setObjectName("widgetSifreli")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widgetSifreli)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widgetPortAyarlari = QtWidgets.QWidget(self.widgetSifreli)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPortAyarlari.sizePolicy().hasHeightForWidth())
        self.widgetPortAyarlari.setSizePolicy(sizePolicy)
        self.widgetPortAyarlari.setMinimumSize(QtCore.QSize(0, 200))
        self.widgetPortAyarlari.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widgetPortAyarlari.setStyleSheet("border: 3px solid  rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"background-color: rgb(230, 230, 230);\n"
"")
        self.widgetPortAyarlari.setObjectName("widgetPortAyarlari")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widgetPortAyarlari)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.widgetPortAyarlari)
        self.label_21.setMinimumSize(QtCore.QSize(0, 38))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 120, 10);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid;\n"
"    border-radius: 10px ;\n"
"}")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_11.addWidget(self.label_21)
        self.framePortAyarlari = QtWidgets.QFrame(self.widgetPortAyarlari)
        self.framePortAyarlari.setMinimumSize(QtCore.QSize(0, 200))
        self.framePortAyarlari.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.framePortAyarlari.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePortAyarlari.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePortAyarlari.setObjectName("framePortAyarlari")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.framePortAyarlari)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelRosAyarlariLog = QtWidgets.QLabel(self.framePortAyarlari)
        self.labelRosAyarlariLog.setMinimumSize(QtCore.QSize(0, 50))
        self.labelRosAyarlariLog.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelRosAyarlariLog.setFont(font)
        self.labelRosAyarlariLog.setStyleSheet("    color: rgb(0, 0, 0);\n"
"    border: 3px solid;\n"
"    border-radius: 10px;")
        self.labelRosAyarlariLog.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRosAyarlariLog.setObjectName("labelRosAyarlariLog")
        self.horizontalLayout_7.addWidget(self.labelRosAyarlariLog)
        self.pushButtonRosAyarlariKaydet = QtWidgets.QPushButton(self.framePortAyarlari)
        self.pushButtonRosAyarlariKaydet.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButtonRosAyarlariKaydet.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRosAyarlariKaydet.setFont(font)
        self.pushButtonRosAyarlariKaydet.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/refresh_icon.png);\n"
"    background-color: rgb(0, 120, 10);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButtonRosAyarlariKaydet.setObjectName("pushButtonRosAyarlariKaydet")
        self.horizontalLayout_7.addWidget(self.pushButtonRosAyarlariKaydet)
        self.gridLayout_15.addLayout(self.horizontalLayout_7, 8, 1, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem14, 7, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.framePortAyarlari)
        self.label_27.setMinimumSize(QtCore.QSize(0, 40))
        self.label_27.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("border:none;")
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_15.addWidget(self.label_27, 0, 1, 1, 1)
        self.lineEditAyarlarHarita1 = QtWidgets.QLineEdit(self.framePortAyarlari)
        self.lineEditAyarlarHarita1.setMinimumSize(QtCore.QSize(150, 40))
        self.lineEditAyarlarHarita1.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAyarlarHarita1.setFont(font)
        self.lineEditAyarlarHarita1.setText("")
        self.lineEditAyarlarHarita1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditAyarlarHarita1.setObjectName("lineEditAyarlarHarita1")
        self.gridLayout_15.addWidget(self.lineEditAyarlarHarita1, 0, 2, 1, 1)
        self.lineEditAyarlarHarita2 = QtWidgets.QLineEdit(self.framePortAyarlari)
        self.lineEditAyarlarHarita2.setMinimumSize(QtCore.QSize(150, 40))
        self.lineEditAyarlarHarita2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAyarlarHarita2.setFont(font)
        self.lineEditAyarlarHarita2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditAyarlarHarita2.setObjectName("lineEditAyarlarHarita2")
        self.gridLayout_15.addWidget(self.lineEditAyarlarHarita2, 2, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.framePortAyarlari)
        self.label_28.setMinimumSize(QtCore.QSize(0, 40))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("border:none;")
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_15.addWidget(self.label_28, 2, 1, 1, 1)
        self.lineEditAyarlarDurakKayitDosyasi = QtWidgets.QLineEdit(self.framePortAyarlari)
        self.lineEditAyarlarDurakKayitDosyasi.setMinimumSize(QtCore.QSize(150, 40))
        self.lineEditAyarlarDurakKayitDosyasi.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAyarlarDurakKayitDosyasi.setFont(font)
        self.lineEditAyarlarDurakKayitDosyasi.setText("")
        self.lineEditAyarlarDurakKayitDosyasi.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditAyarlarDurakKayitDosyasi.setObjectName("lineEditAyarlarDurakKayitDosyasi")
        self.gridLayout_15.addWidget(self.lineEditAyarlarDurakKayitDosyasi, 5, 2, 1, 1)
        self.lineEditAyarlarAGVicon = QtWidgets.QLineEdit(self.framePortAyarlari)
        self.lineEditAyarlarAGVicon.setMinimumSize(QtCore.QSize(150, 40))
        self.lineEditAyarlarAGVicon.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAyarlarAGVicon.setFont(font)
        self.lineEditAyarlarAGVicon.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditAyarlarAGVicon.setObjectName("lineEditAyarlarAGVicon")
        self.gridLayout_15.addWidget(self.lineEditAyarlarAGVicon, 4, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.framePortAyarlari)
        self.label_33.setMinimumSize(QtCore.QSize(0, 40))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("border:none;")
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_15.addWidget(self.label_33, 5, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.framePortAyarlari)
        self.label_34.setMinimumSize(QtCore.QSize(0, 40))
        self.label_34.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("border:none;")
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_15.addWidget(self.label_34, 4, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.framePortAyarlari)
        self.gridLayout_7.addWidget(self.widgetPortAyarlari, 1, 2, 2, 1)
        self.toolBox_operator_add_remove = QtWidgets.QToolBox(self.widgetSifreli)
        self.toolBox_operator_add_remove.setMaximumSize(QtCore.QSize(500, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.toolBox_operator_add_remove.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox_operator_add_remove.setFont(font)
        self.toolBox_operator_add_remove.setStyleSheet("border: 0px solid  rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"")
        self.toolBox_operator_add_remove.setObjectName("toolBox_operator_add_remove")
        self.addoperator = QtWidgets.QWidget()
        self.addoperator.setGeometry(QtCore.QRect(0, 0, 292, 156))
        self.addoperator.setObjectName("addoperator")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.addoperator)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_18 = QtWidgets.QLabel(self.addoperator)
        self.label_18.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border:none;\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 1, 0, 1, 1)
        self.pushButtonOperatorEkle = QtWidgets.QPushButton(self.addoperator)
        self.pushButtonOperatorEkle.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOperatorEkle.setFont(font)
        self.pushButtonOperatorEkle.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/add_user.png);\n"
"    background-color: rgb(0, 120, 10);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButtonOperatorEkle.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonOperatorEkle.setObjectName("pushButtonOperatorEkle")
        self.gridLayout_9.addWidget(self.pushButtonOperatorEkle, 3, 1, 1, 1)
        self.lineEditOperatorisimEkle = QtWidgets.QLineEdit(self.addoperator)
        self.lineEditOperatorisimEkle.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditOperatorisimEkle.setFont(font)
        self.lineEditOperatorisimEkle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.lineEditOperatorisimEkle.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOperatorisimEkle.setObjectName("lineEditOperatorisimEkle")
        self.gridLayout_9.addWidget(self.lineEditOperatorisimEkle, 0, 1, 1, 1)
        self.lineEditOperatorSifreEkle = QtWidgets.QLineEdit(self.addoperator)
        self.lineEditOperatorSifreEkle.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditOperatorSifreEkle.setFont(font)
        self.lineEditOperatorSifreEkle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.lineEditOperatorSifreEkle.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOperatorSifreEkle.setObjectName("lineEditOperatorSifreEkle")
        self.gridLayout_9.addWidget(self.lineEditOperatorSifreEkle, 1, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem15, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.addoperator)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border:none;")
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/add_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox_operator_add_remove.addItem(self.addoperator, icon4, "")
        self.removeoperator = QtWidgets.QWidget()
        self.removeoperator.setGeometry(QtCore.QRect(0, 0, 343, 139))
        self.removeoperator.setObjectName("removeoperator")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.removeoperator)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.comboBoxOperatorSil = QtWidgets.QComboBox(self.removeoperator)
        self.comboBoxOperatorSil.setMinimumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxOperatorSil.setFont(font)
        self.comboBoxOperatorSil.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.comboBoxOperatorSil.setObjectName("comboBoxOperatorSil")
        self.gridLayout_17.addWidget(self.comboBoxOperatorSil, 0, 1, 1, 1)
        self.pushButtonOperatorSil = QtWidgets.QPushButton(self.removeoperator)
        self.pushButtonOperatorSil.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOperatorSil.setFont(font)
        self.pushButtonOperatorSil.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/delete.png);\n"
"    background-color: rgb(0, 120, 10);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButtonOperatorSil.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonOperatorSil.setObjectName("pushButtonOperatorSil")
        self.gridLayout_17.addWidget(self.pushButtonOperatorSil, 3, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.removeoperator)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_17.addWidget(self.line_3, 1, 1, 1, 1)
        self.pushButtonOperatorSilYenile = QtWidgets.QPushButton(self.removeoperator)
        self.pushButtonOperatorSilYenile.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOperatorSilYenile.setFont(font)
        self.pushButtonOperatorSilYenile.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/refresh_icon.png);\n"
"    background-color: rgb(0, 120, 10);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButtonOperatorSilYenile.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonOperatorSilYenile.setObjectName("pushButtonOperatorSilYenile")
        self.gridLayout_17.addWidget(self.pushButtonOperatorSilYenile, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem16, 2, 1, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox_operator_add_remove.addItem(self.removeoperator, icon5, "")
        self.gridLayout_7.addWidget(self.toolBox_operator_add_remove, 1, 3, 1, 1)
        self.gridLayout_6.addWidget(self.widgetSifreli, 2, 1, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons/settings_icon_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetEtiketOzellikleri.addTab(self.AYARLAR, icon6, "")
        self.horizontalLayout_11.addWidget(self.tabWidgetEtiketOzellikleri)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetEtiketOzellikleri.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_amr_secim.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonRefresh, self.listWidgetLog)
        MainWindow.setTabOrder(self.listWidgetLog, self.pushButtonGirisYap)
        MainWindow.setTabOrder(self.pushButtonGirisYap, self.pushButtonCikisYap)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ana Pencere"))
        self.label_48.setText(_translate("MainWindow", "AGV 1"))
        self.labelAMR1Status.setText(_translate("MainWindow", "OFFLINE"))
        self.label_49.setText(_translate("MainWindow", "AGV 2"))
        self.labelAMR2Status.setText(_translate("MainWindow", "OFFLINE"))
        self.label_6.setText(_translate("MainWindow", "PLC   "))
        self.labelPLCStatus.setText(_translate("MainWindow", "OFFLINE"))
        self.label_3.setText(_translate("MainWindow", "CONNECTION STATUS"))
        self.labelCevrimSuresi.setText(_translate("MainWindow", "*"))
        self.label_10.setText(_translate("MainWindow", "            CYCLE"))
        self.butonKapat.setText(_translate("MainWindow", "CLOSE"))
        self.label_22.setText(_translate("MainWindow", "..."))
        self.labelYazdirmaZamani.setText(_translate("MainWindow", "0"))
        self.labelSonBarkodunBasilmaDurumu.setText(_translate("MainWindow", "*"))
        self.pushButtonRefresh.setText(_translate("MainWindow", "REFRESH the PAGE"))
        self.tabWidgetEtiketOzellikleri.setTabText(self.tabWidgetEtiketOzellikleri.indexOf(self.ANASAYFA), _translate("MainWindow", "HOME PAGE"))
        self.label_2.setText(_translate("MainWindow", "ROBOT CONTROL"))
        self.buton_ileri.setText(_translate("MainWindow", "FORWARD"))
        self.buton_geri.setText(_translate("MainWindow", "BACK"))
        self.buton_dur.setText(_translate("MainWindow", "STOP"))
        self.buton_sol.setText(_translate("MainWindow", "LEFT"))
        self.buton_sag.setText(_translate("MainWindow", "RIGHT"))
        self.label_8.setText(_translate("MainWindow", "SELECT AGV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "SELECT AGV "))
        self.label_lineer_hiz.setText(_translate("MainWindow", "0.0"))
        self.label_donus_acisi.setText(_translate("MainWindow", "0.0"))
        self.label_11.setText(_translate("MainWindow", "Position Y(m):"))
        self.label_konum_y.setText(_translate("MainWindow", "0.0"))
        self.label_konum_x.setText(_translate("MainWindow", "0.0"))
        self.label_12.setText(_translate("MainWindow", "Rotation AngleX:"))
        self.label_5.setText(_translate("MainWindow", "Angular Velocity(rad/s):"))
        self.label_acisal_hiz.setText(_translate("MainWindow", "0.0"))
        self.label_7.setText(_translate("MainWindow", "Linear Velocity(m/s):"))
        self.label_9.setText(_translate("MainWindow", "Position X(m):"))
        self.label_19.setText(_translate("MainWindow", "State of Charge:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "AGV 1"))
        self.label_20.setText(_translate("MainWindow", "Linear Velocity(m/s):"))
        self.label_lineer_hiz_2.setText(_translate("MainWindow", "0.0"))
        self.label_14.setText(_translate("MainWindow", "Position X(m):"))
        self.label_17.setText(_translate("MainWindow", "Angular Velocity(rad/s):"))
        self.label_15.setText(_translate("MainWindow", "Position Y(m):"))
        self.label_konum_x_2.setText(_translate("MainWindow", "0.0"))
        self.label_24.setText(_translate("MainWindow", "Rotation AngleX:"))
        self.label_konum_y_2.setText(_translate("MainWindow", "0.0"))
        self.label_acisal_hiz_2.setText(_translate("MainWindow", "0.0"))
        self.label_donus_acisi_2.setText(_translate("MainWindow", "0.0"))
        self.label_23.setText(_translate("MainWindow", "State of Charge:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "AGV 2"))
        self.label_25.setText(_translate("MainWindow", "Linear Velocity:"))
        self.label_30.setText(_translate("MainWindow", "Position X(m):"))
        self.label_31.setText(_translate("MainWindow", "Position Y(m):"))
        self.label_32.setText(_translate("MainWindow", "Rotation AngleX:"))
        self.label_26.setText(_translate("MainWindow", "Angular Velocity:"))
        self.label_lineer_hiz_toplam.setText(_translate("MainWindow", "0.0"))
        self.label_acisal_hiz_toplam.setText(_translate("MainWindow", "0.0"))
        self.label_konum_x_toplam.setText(_translate("MainWindow", "0.0"))
        self.label_konum_y_toplam.setText(_translate("MainWindow", "0.0"))
        self.label_donus_acisi_toplam.setText(_translate("MainWindow", "0.0"))
        self.label_36.setText(_translate("MainWindow", "Linear Velocity:"))
        self.label_37.setText(_translate("MainWindow", "Position X(m):"))
        self.label_38.setText(_translate("MainWindow", "Position Y(m):"))
        self.label_39.setText(_translate("MainWindow", "Rotation AngleX:"))
        self.label_40.setText(_translate("MainWindow", "Angular Velocity:"))
        self.label_lineer_hiz_toplam_2.setText(_translate("MainWindow", "0.0"))
        self.label_acisal_hiz_toplam_2.setText(_translate("MainWindow", "0.0"))
        self.label_konum_x_toplam_2.setText(_translate("MainWindow", "0.0"))
        self.label_konum_y_toplam_2.setText(_translate("MainWindow", "0.0"))
        self.label_donus_acisi_toplam_2.setText(_translate("MainWindow", "0.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget1), _translate("MainWindow", "MULTIPLE AGV"))
        self.butonKapat_5.setText(_translate("MainWindow", "CLOSE"))
        self.tabWidgetEtiketOzellikleri.setTabText(self.tabWidgetEtiketOzellikleri.indexOf(self.DATALAR), _translate("MainWindow", "CONTROL"))
        self.label_41.setText(_translate("MainWindow", "VEHICLE STATION TRACKING"))
        self.label_47.setText(_translate("MainWindow", "STATION LIST"))
        self.tableWidget_durak_listesi.setSortingEnabled(True)
        item = self.tableWidget_durak_listesi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STATION NAME"))
        item = self.tableWidget_durak_listesi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "POSITION X"))
        item = self.tableWidget_durak_listesi.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "POSITION Y"))
        item = self.tableWidget_durak_listesi.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "POSITION Z"))
        item = self.tableWidget_durak_listesi.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NOTE"))
        self.label_durak_sayici.setText(_translate("MainWindow", "0"))
        self.pushbuton_durak_liste_yenile.setText(_translate("MainWindow", "REFRESH LIST"))
        self.label_durak_log.setText(_translate("MainWindow", "Hata yok"))
        self.label_42.setText(_translate("MainWindow", "CURRENT LOCATION AGV 1 :"))
        self.comboBox_amr_secim.setCurrentText(_translate("MainWindow", "SELECT AGV"))
        self.comboBox_amr_secim.setItemText(0, _translate("MainWindow", "SELECT AGV"))
        self.comboBox_amr_secim.setItemText(1, _translate("MainWindow", "AGV 1"))
        self.comboBox_amr_secim.setItemText(2, _translate("MainWindow", "AGV 2"))
        self.label_45.setText(_translate("MainWindow", "STATION NOTE:"))
        self.pushButton_durak_kaydet.setText(_translate("MainWindow", "SAVE STATION"))
        self.label_44.setText(_translate("MainWindow", "STATION NAME"))
        self.label_90.setText(_translate("MainWindow", "CURRENT LOCATION AGV 2 :"))
        self.label_46.setText(_translate("MainWindow", "DELETE STATION"))
        self.pushButton_durak_sil.setText(_translate("MainWindow", "DELETE STATION"))
        self.butonKapat_4.setText(_translate("MainWindow", "CLOSE"))
        self.tabWidgetEtiketOzellikleri.setTabText(self.tabWidgetEtiketOzellikleri.indexOf(self.tab_4), _translate("MainWindow", "STATION"))
        self.pushButtonGirisYap.setText(_translate("MainWindow", "LOGIN"))
        self.pushButtonCikisYap.setText(_translate("MainWindow", "LOG OUT"))
        self.butonKapat_3.setText(_translate("MainWindow", "CLOSE"))
        self.label_21.setText(_translate("MainWindow", "ROS SETTINGS"))
        self.labelRosAyarlariLog.setText(_translate("MainWindow", "*"))
        self.pushButtonRosAyarlariKaydet.setText(_translate("MainWindow", "SAVE"))
        self.label_27.setText(_translate("MainWindow", "MAP 1:  "))
        self.label_28.setText(_translate("MainWindow", "MAP 2:  "))
        self.label_33.setText(_translate("MainWindow", "STATION SAVE FILE:"))
        self.label_34.setText(_translate("MainWindow", "AGV ICON:  "))
        self.label_18.setText(_translate("MainWindow", "PASSWORD:"))
        self.pushButtonOperatorEkle.setText(_translate("MainWindow", "ADD OPERATOR"))
        self.label_16.setText(_translate("MainWindow", "NAME:"))
        self.toolBox_operator_add_remove.setItemText(self.toolBox_operator_add_remove.indexOf(self.addoperator), _translate("MainWindow", "ADD OPERATOR"))
        self.pushButtonOperatorSil.setText(_translate("MainWindow", "REMOVE OPERATOR"))
        self.pushButtonOperatorSilYenile.setText(_translate("MainWindow", "REFRESH"))
        self.toolBox_operator_add_remove.setItemText(self.toolBox_operator_add_remove.indexOf(self.removeoperator), _translate("MainWindow", "REMOVE OPERATOR"))
        self.tabWidgetEtiketOzellikleri.setTabText(self.tabWidgetEtiketOzellikleri.indexOf(self.AYARLAR), _translate("MainWindow", "SETTINGS"))

import ikonlar_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

